[package]
name = "huffman-idk"
description = "I was bored"
license-file = "LICENSE"
version = "0.1.0"
edition = "2021"

[dependencies]
baa = "0.14.5"

[dev-dependencies]
insta = "1.41.1"
paste = "1.0.15"
proptest = "1.5.0"
